services:
    _defaults:
        public: true

    Acme\Bundle\DemoBundle\Controller\DocumentController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
